name: Docker CI/CD pipeline

on:
  push:
    branches:
      -main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: monaduvvapu/monaduvvapu-website:{{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key:  ${{ secrets.EC2_PRIVATE_KEY }}
          script: | 
            docker stop monaduvvapu-website || true
            docker rm monaduvvapu-website || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/monaduvvapu-website:${{ github.sha }}
            docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/monaduvvapu-website:${{ github.sha }}
          
      
